application:
  enviroment: local
  webfrontDomain: http://localhost:3000

server:
  contextPath: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qa?useSSL=false
    username: root
    password:
    validationQuery: SELECT 1
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: MercuryConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: false

redis:
  host: localhost
  port: 6379

logging:
  level.org:
    springframework.web: DEBUG
    hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE